version: "2.4"

volumes:
  postgres_data:

networks:
  backend:

services:
  postgres:
    extends: { file: common-services.yml, service: postgres }
    networks: [ "backend" ]

  web:
    image: vovimayhem/dotnet-core-postgresql:latest
    build:
      context: ./MvcMovie
      dockerfile: Dockerfile
      target: release

    ports:
    # We'll bind our host's port 5000 to the app's port 5000, so we can use our
    # browsers to see it:
    - ${DEMO_WEB_PORT:-5000}:5000

    depends_on: [ "postgres" ]
    networks: [ "backend" ]


    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    command: dotnet MvcMovie.dll

    environment:
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432/demo_development
      PORT: 5000
